version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-stack-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/aram
      - SPRING_DATASOURCE_USERNAME=jelly
      - SPRING_DATASOURCE_PASSWORD=pinky030566
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-stack-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    container_name: ai-stack-db
    environment:
      - POSTGRES_DB=aram
      - POSTGRES_USER=jelly
      - POSTGRES_PASSWORD=pinky030566
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 