apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-stack-demo
  labels:
    app: ai-stack-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-stack-demo
  template:
    metadata:
      labels:
        app: ai-stack-demo
    spec:
      containers:
      - name: ai-stack-demo
        image: ai-stack-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        # 存活探針 - 檢查應用程序是否運行
        livenessProbe:
          httpGet:
            path: /api/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3
        # 就緒探針 - 檢查應用程序是否準備好接收流量
        readinessProbe:
          httpGet:
            path: /api/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        # Actuator 健康檢查探針
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 30
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: JAVA_OPTS
          value: "-Xmx768m -Xms256m"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-stack-demo-service
spec:
  selector:
    app: ai-stack-demo
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP 