# Server Configuration
server:
  port: 8080

# Spring Configuration
spring:
  # 資料庫配置
  datasource:
    url: jdbc:postgresql://13.55.54.92:5432/aram
    username: jelly
    password: pinky030566
    driver-class-name: org.postgresql.Driver
  
jpa:
  hibernate:
    ddl-auto: none
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp.use_jdbc_metadata_defaults: false
      check_nullability: false
      schema_validation.enabled: false
      naming:
        # 使用這個策略會自動將駝峰式轉換為下劃線命名
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # Async Executor Configuration
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
      thread-name-prefix: async-task-
  
  # Security Filter 配置
  security:
    filter:
      dispatcher-types: REQUEST,ERROR,ASYNC
      
  # 添加 MVC 路徑匹配策略
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# JWT 配置
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 3600000 # 1小時 (毫秒)

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  show-actuator: true
  packagesToScan: com.example.demo.controller

# Logging Configuration
logging:
  level:
    com.example.demo: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.task: DEBUG
    org.springframework.security.web: DEBUG
    org.springdoc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"